config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/auth/google_oauth2/callback', to: 'sessions#create', as: 'callback'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/location', to: 'location#show'
  post '/location', to: 'location#create'

  post '/user_bars', to: 'user_bars#create'
  delete '/user_bars', to: 'user_bars#destroy'

  resources :deals, only: [:index]
  resource :map, only: [:show], controller: 'map'
  resources :bars, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord
  validates_presence_of :name, :address, :longitude, :latitude, :open, :close, :hh_start, :hh_end, :message, :deals, :owner_email
  serialize :open
  serialize :close
  serialize :hh_start
  serialize :hh_end
  has_many :choices
  has_many :user_bars
  has_many :users, through: :user_bars

end

app/models/choice.rb
class Choice < ApplicationRecord
  validates_presence_of :user_id, :bar_id
  belongs_to :user
  belongs_to :bar

end

app/models/location.rb
class Location < ApplicationRecord
  validates_presence_of :user_id, :longitude, :latitude
  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :uid, uniqueness: true
  validates :email, uniqueness: true, :case_sensitive => false
  has_many :locations
  has_many :choices
  has_many :user_bars
  has_many :bars, through: :user_bars

  def self.from_omniauth(auth)
    where(uid: auth.uid).first_or_initialize.tap do |user|
      user.uid = auth.uid
      user.email = auth.info.email
      user.save!
    end
  end
end

app/models/user_bar.rb
class UserBar < ApplicationRecord
  validates_presence_of :user_id, :bar_id
  belongs_to :user
  belongs_to :bar
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :bar_owner?

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def bar_owner?
    Bar.find_by_owner_email(current_user.email) if (current_user && Bar.find_by_owner_email(current_user.email))
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def edit
    render file: "/public/404" unless bar_owner?.id == params[:id].to_i
    @presenter = BarPresenter.new(bar_owner?)
  end

  def update
    @bar = Bar.find(params[:id])
    if bar_params['message']
      @bar.message = bar_params['message']
    else
      edit_bar_deals
    end
    if @bar.save
      flash[:successs] = @bar.name + " successfully updated."
      redirect_to edit_bar_path(@bar)
    else
      render :edit
    end
  end

  private
  def bar_params
    params.require(:bar).permit(:message, open: days_of_week, close: days_of_week, hh_start: days_of_week, hh_end: days_of_week, deals: hh_keys)
  end

  def days_of_week
    [:Sunday, :Monday, :Tuesday, :Wednesday, :Thursday, :Friday, :Saturday]
  end

  def hh_keys
    [:first, :second, :third, :fourth, :fifth]
  end

  def new_hh_deals
    hh_keys.map do |deal|
      bar_params[:deals][deal]      
    end
  end

  def edit_bar_deals
    @bar.open[bar_params.values[0].keys.first.to_sym] = [bar_params.values[0].values.first]
    @bar.close[bar_params.values[1].keys.first.to_sym] = [bar_params.values[1].values.first]
    @bar.hh_start[bar_params.values[2].keys.first.to_sym] = [bar_params.values[2].values.first]
    @bar.hh_end[bar_params.values[3].keys.first.to_sym] = [bar_params.values[3].values.first]
    @bar.deals[bar_params.values[0].keys.first] = new_hh_deals
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { render json: [current_user.last_location, DealsPresenter.new(current_user.last_long, current_user.last_lat).nearby_bars] }
    end
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  def create
    long = params[:long]
    lat = params[:lat]
    presenter = DealsPresenter.new(long, lat)
    current_user.update_attributes(last_location: presenter.current_address, last_long: long, last_lat: lat)
    current_user.locations.create(longitude: long, latitude: lat) unless recently_logged_location
    redirect_to deals_path
  end

  private
  def recently_logged_location
    current_user.locations.where(created_at: (Time.zone.now.utc - 1.hour)..Time.zone.now.utc).any?
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def show
    @presenter = MapPresenter.new(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(user_auth)
    session[:user_id] = user.id
    redirect_to deals_path
  end

  def destroy
    UserBar.where(user_id: current_user.id).delete_all
    current_user.update_attributes(last_location: nil, last_long: nil, last_lat: nil)
    reset_session
    redirect_to root_path
  end

  private
  def user_auth
    request.env['omniauth.auth']
  end
end

app/controllers/user_bar_controller.rb
class UserBarController < ApplicationController
  
  def create
    current_user.user_bars.create(user_bar_params) unless logged_user_bar
    current_user.choices.create(click: true, bar_id: user_bar_params[:bar_id]) unless logged_choice_today
    redirect_to deals_path
  end

  def destroy
    current_user.user_bars.where(user_bar_params).destroy_all if logged_user_bar
    current_user.choices.create(click: false, bar_id: user_bar_params[:bar_id]) unless logged_choice_today
  end

  private
  def user_bar_params
    params.require(:user_bar).permit(:bar_id)
  end

  def logged_user_bar
    current_user.user_bars.find_by_bar_id(user_bar_params[:bar_id])
  end

  def logged_choice_today
    current_user.choices.where(bar_id: user_bar_params[:bar_id], created_at: Time.zone.now.utc.all_day).any?
  end
end

app/controllers/user_bars_controller.rb
class UserBarsController < ApplicationController
  def create
    current_user.user_bars.create(user_bar_params) unless logged_user_bar
    current_user.choices.create(click: true, bar_id: user_bar_params[:bar_id]) unless logged_choice_today
    redirect_to deals_path
  end

  def destroy
    current_user.user_bars.where(user_bar_params).destroy_all if logged_user_bar
    current_user.choices.create(click: false, bar_id: user_bar_params[:bar_id]) unless logged_choice_today
  end

  private

  def user_bar_params
    params.require(:user_bar).permit(:bar_id)
  end

  def logged_user_bar
    current_user.user_bars.find_by_bar_id(user_bar_params[:bar_id])
  end

  def logged_choice_today
    current_user.choices.where(bar_id: user_bar_params[:bar_id], created_at: Time.zone.now.utc.all_day).any?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bars/edit.html.erb
<h1 class="flex-row-center edit-title"><%= @presenter.bar.name %></h1>
<p class="flex-row-center rubik-thin"><%= @presenter.bar.address %></p>
<div class="flex-row-center">
  <%= form_for @presenter.bar do |f| %>
    <article class="input-fields">
      <div class="ui form inline right-margin">
          <%= f.label :message %>
          <%= f.text_area :message, class: "input-color", cols: 30, rows: 5 %>
      </div>
    </article>
    <%= f.submit "Update Message", class: "ui button bar-edit-submit" %>
  <% end %>
</div>
</br>
<main>
  <% ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].each do |day| %>
    <div class="line-break"></div>
    <div class="edit-days", id="<%= day %>">
      <article class="day-and-chart">
        <h1 class="rubik-thin"><%= day %></h1>
        <div class="chart-container">
          <canvas id="<%= day.downcase %>Chart"></canvas> 
        </div>
      </article>
      <article>
        <%= form_for @presenter.bar do |f| %>
          <article class="input-fields">
            <div class="vert-fields">
              <div class="ui input">
                <%= f.label :open %>
                <%= f.fields_for :open, OpenStruct.new(@presenter.bar.open) do |ff| %>
                  <% ff.text_field day %>
                <% end %>
              </div>
              </br>
              </br>
              <div class="ui input">
                <%= f.label :close %>
                <%= f.fields_for :close, OpenStruct.new(@presenter.bar.close) do |ff| %>
                  <% ff.text_field day %>
                <% end %>
              </div>
            </div>
          </article>
          <article class="input-fields">
            <div class="vert-fields">
              <div class="ui input">
                <%= f.label :Happy_hour_start %>
                <%= f.fields_for :hh_start, OpenStruct.new(@presenter.bar.hh_start) do |ff| %>
                  <% ff.text_field day %>
                <% end %>
              </div>
              </br>
              </br>
              <div class="ui input">
                <%= f.label :Happy_hour_end %>
                <%= f.fields_for :hh_end, OpenStruct.new(@presenter.bar.hh_end) do |ff| %>
                  <% ff.text_field day %>
                <% end %>
              </div>
            </div>
          </article>
          <article class="input-fields">
            <div class="vert-fields">
              <%= f.label :deals %>
              <div class="ui input", id="deal-fields">
                <%= f.fields_for :deals, OpenStruct.new(@presenter.bar.deals)[day] do |ff| %>
                  <% ff.text_field :first %>
                <% end %>
                <%= f.fields_for :deals, OpenStruct.new(@presenter.bar.deals)[day] do |ff| %>
                  <% ff.text_field :second %>
                <% end %>
                <%= f.fields_for :deals, OpenStruct.new(@presenter.bar.deals)[day] do |ff| %>
                  <% ff.text_field :third %>
                <% end %>
                <%= f.fields_for :deals, OpenStruct.new(@presenter.bar.deals)[day] do |ff| %>
                  <% ff.text_field :fourth %>
                <% end %>
                <%= f.fields_for :deals, OpenStruct.new(@presenter.bar.deals)[day] do |ff| %>
                  <% ff.text_field :fifth %>
                <% end %>
              </div>
            </div>
          </article>
          <div class="vert-fields bar-edit-submit">
            <%= f.submit "Update #{day}", class: "ui button" %>
          </div>
        <% end %>
      </article>
    </div>
  <% end %>
</main>

<%= javascript_include_tag 'bars' %>

app/views/deals/index.html.erb
<div class="flex-row-center">
	<%= image_tag "location", height: "40px", width: "40px", id: "location-image" %>
	<p class="rubik-thin", id="location-text">
		<%= image_tag "load-bar", height: "25px", width: "auto" %>
	</p>
</div>
<main class="flex-row-center card-holder">
	<div class="bar-card">
		<p class="rubik-thin flex-row-center", id="dc-name"></br></p>
		<p class="rubik-thin flex-row-center", id="dc-address"></br></p>
		<p class="rubik-thin flex-row-center", id="dc-hours"></br></p>
		<p class="rubik-thin flex-row-center", id="dc-hh_hours"></br></p>
		<p class="rubik-thin flex-row-center", id="dc-message"></br></p>
		<p class="rubik-thin flex-row-center", id="dc-deals1"></br></p>
		<p class="rubik-thin flex-row-center", id="dc-deals2"></br></p>
		<p class="rubik-thin flex-row-center", id="dc-deals3"></br></p>
		<p class="rubik-thin flex-row-center", id="dc-deals4"></br></p>
		<p class="rubik-thin flex-row-center", id="dc-deals5"></br></p>
		<div class="flex-row-center", id="horizontal-line"></div>
		<div class="flex-row-center", id="button-box">
			<div class="click-box", id="dislike">
				<input type="image" src="assets/negative.svg", height="100px", width="100px", class="card-buttons" />
			</div>
			<div id="vertical-line"></div>
			<div class="click-box", id="like">
				<input type="image" src="assets/positive.svg", height="100px", width="100px", class="card-buttons" />
			</div>
		</div>
	</div>
	<div class="bar-card-after"></div>
</main>

<%= javascript_include_tag 'deals' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarHopBuddy</title>
    <%= csrf_meta_tags %>

    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.css' rel='stylesheet' />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" type="text/css" href='https://fonts.googleapis.com/css?family=Rubik'/>
    <meta name=viewport content='width=750'>
    <%= favicon_link_tag asset_path("favicon-clock.png"), :rel => 'icon', :type =>  'image/png' %>
    <% if current_page?(root_path) %>
      <meta http-equiv="refresh" content="3;url=https://barhopbuddy.herokuapp.com/auth/google_oauth2" />
    <% end %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <% unless current_page?(root_path) %>
      <nav class="ui borderless menu grid">
        <div class="five wide column fitted item">
          <span class="left-pad nav-app-name">BarH</span>
          <div class="nav-image">
            <%= image_tag "five-oclock-white", height: "23px", width: "23px"%>
          </div>
          <span class="nav-app-name">pBuddy</span>
        </div>
        <% if current_page?(deals_path) %>
          <div class="six wide column item flex-row-center">
            <%= button_to 'Find Your Bars', map_path, class: "large ui button", method: :get %>
          </div>
        <% elsif current_page?(map_path) || current_page?(edit_bar_path(bar_owner?)) %>
          <div class="six wide column item flex-row-center">
            <%= button_to 'Select Your Bars', deals_path, class: "large ui button", method: :get %>
          </div>
        <% end %>
        <div class="five wide column right item flex-row-r">
          <%= button_to 'Log Out', logout_path, class: "ui button", id: "logout", method: :delete %>
          <% if bar_owner? && !current_page?(edit_bar_path(bar_owner?)) %>
            <%= button_to 'Edit Your Bar', edit_bar_path(bar_owner?), class: "ui button", method: :get %>
          <% end %>
        </div>
      </nav>
    <% end %>
      <% flash.each do |type, message| %>
        <div class="ui floating message rubik-thin", id="flash">
          <%= content_tag :div, message.html_safe, class: type %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/map/show.html.erb
<main class="flex-row-center">
  <div id="map"></div>
</main>

<%= javascript_include_tag 'map' %>

app/views/welcome/index.html.erb
<main class="bg">
  <div class="splash-app-name">
    <h1 class="reset-margin title">BarH</h1>
    <%= image_tag("five-oclock-white", class: "flex-col", width: "42px", height: "42px") %>
    <h1 class="reset-margin title">pBuddy</h1>
  </div>
</main>